version: 0.0
os: linux
files:
  - source: aws/ec2/script
    destination: /home/ec2-user/script
hooks:
  ApplicationStop:
    - location: aws/ec2/script/application-stop.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: aws/ec2/script/before-install.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: aws/ec2/script/application-start.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: aws/ec2/script/validate-service.sh
      timeout: 30
      runas: ec2-user