version: 0.0
os: linux
files:
  - source: scripts/ec2
    destination: /home/ec2-user/scripts
hooks:
  BeforeInstall:
    - location: scripts/ec2/before-install.sh
      timeout: 30
      runas: ec2-user
  ApplicationStart:
    - location: scripts/ec2/application-start.sh
      timeout: 120
      runas: ec2-user