version: "3.9"
services:
  my-app:
    container_name: my-app
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - PROJECT_NAME=${PROJECT_NAME}
        - VERSION=${VERSION}
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - redis-net
    depends_on:
      - redis-service
  redis-service:
    image: redis/redis-stack-server:latest
    container_name: standalone-redis
    ports:
      - "6379:6379"
    networks:
      - redis-net

networks:
  redis-net:
    external: true
    name: redis-network