version: "3.9"
services:
  my-app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - PROJECT_NAME=${PROJECT_NAME}
        - VERSION=${VERSION}
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis-service
  redis-service1:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
  redis-service2:
    image: redis/redis-stack-server:latest
    ports:
      - "6380:6379"