version: "3.9"
services:
  my-app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - PROJECT_NAME=${PROJECT_NAME}
        - VERSION=${VERSION}
    env_file:
      - .env
    ports:
      - "8080:8080"
  redis-service:
    image: redis:latest
    ports:
      - "6379:6379"