spring:
  redis:
    host: localhost
    port: 6380

server:
  rate-limiter:
    properties:
      # type options includes: `sliding-window`, `fixed-window`, `token-bucket`, `leaky-bucket`
      # `sliding-window` requires limitCapacity & window-duration
      # `fixed-window` requires limitCapacity & window-duration
      # `token-bucket` requires limitCapacity & refillRate
      # `leaky-bucket` requires limitCapacity & leakingRate
      type: sliding-window
      limitCapacity: 10
      windowDuration: 60 # in seconds
      refillRate: 10 # pieces/min
      leakingRate: 10 # pieces/min