spring:
  banner:
    location: classpath:banner/banner.txt
  redis:
    # Connect to another Docker container written in docker-compose.yaml
    host: redis-service
    # for local test
#    host: localhost
    port: 6379

server:
  rate-limiter:
    properties:
      # type options includes: `sliding-window`, `fixed-window`, `token-bucket`, `leaky-bucket`
      # `sliding-window` requires limitCapacity & window-duration
      # `fixed-window` requires limitCapacity & window-duration
      # `token-bucket` requires limitCapacity & refillRate
      # `leaky-bucket` requires limitCapacity & leakingRate
      type: token-bucket
      limitCapacity: 10
      windowDuration: 60 # in seconds
      refillRate: 10 # pieces/min
      leakingRate: 10 # pieces/min
  bloom-filter:
    properties:
      expectedSize: 1000
      falsePositiveRate: 0.001