version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0
  aws-cli: circleci/aws-cli@5.1.2
#  aws-code-deploy: circleci/aws-code-deploy@3.0.0

parameters:
  GIT_LATEST_COMMIT_SHA_KEY:
    type: string
    default: "last_commit_sha"

executors:
  test-executor:
    docker:
      - image: cimg/openjdk:17.0.13-node

jobs:
  build-and-test:
    executor: test-executor
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker: # Enable Docker for Testcontainers
          version: default
      - gradle/with_cache:
          steps:
            - run:
                command: gradle clean test
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Record the latest commit id in CircleCI's env file
          command: echo "export << pipeline.parameters.GIT_LATEST_COMMIT_SHA_KEY >>=$(git rev-parse HEAD)" >> $BASH_ENV
      - aws-cli/setup:
          profile_name: default
      - run:
          command: |
            aws deploy create-deployment \
            --application-name redis-impl \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name redis-impl-dg \
            --description "Deployed from CircleCI" \
            --github-location repository=Carricaner/redis-implement,commitId=$<< pipeline.parameters.GIT_LATEST_COMMIT_SHA_KEY >> \
            | jq -r ".deploymentId"

workflows:
  build-test-deploy:
    jobs:
#      - build-and-test:
#          filters:
#            branches:
#              only:
#                - dev
#                - prod
#                - main
      - deploy:
#          requires:
#            - build-and-test
          filters:
            branches:
              only:
                - prod
                - main