version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0
#  aws-cli: circleci/aws-cli@5.1.2
#  aws-code-deploy: circleci/aws-code-deploy@3.0.0

executors:
  test-executor:
    docker:
      - image: cimg/openjdk:17.0.13-node

jobs:
  build-and-test:
    executor: test-executor
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker: # Enable Docker for Testcontainers
          version: default
      - gradle/with_cache:
          steps:
            - run:
                command: gradle clean test

workflows:
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
                - dev
                - prod