version: "3.9"
services:
  app:
    build:
      context: ../../
      dockerfile: ./env/dev/Dockerfile
      args:
        - PROJECT_NAME=${PROJECT_NAME}
        - VERSION=${VERSION}
    env_file:
      - .env
    ports:
      - "8081:8081"