singleServerConfig:
  address: "redis-16463.c54.ap-northeast-1-2.ec2.redns.redis-cloud.com:16463"
  username: "default"
  password: "Uw9cC07ieFTEUHx6zGLQu84wnFhaQaOT"
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  clientName: null
#clusterServersConfig:
#  idleConnectionTimeout: 10000
#  connectTimeout: 10000
#  timeout: 3000
#  retryAttempts: 3
#  retryInterval: 1500
#  password: null
#  subscriptionsPerConnection: 5
#  clientName: null
#  nodeAddresses:
#    - "redis://127.0.0.1:6379"
#    - "redis://127.0.0.1:6380"
#  scanInterval: 1000
#  readMode: "SLAVE"